//! Locale catalogue for every user-facing diagnostic string. One field
//! per message in `Strings`; a locale table is a complete struct literal,
//! so a missing translation is a compile error. Templates are `std.fmt`
//! format strings evaluated at comptime per locale (via `inline else` in
//! diag.zig), so a template whose placeholders do not match its call
//! site's arguments is also a compile error — in every locale.
//!
//! Keep templates in natural word order for their language; use positional
//! placeholders ({0s}, {1s}) when a translation needs a different argument
//! order than the call site supplies.

pub const Lang = enum {
    en,
    de,
};

pub const Strings = struct {

    // Frontend framing labels.
    label_error: []const u8,
    label_warning: []const u8,
    label_note: []const u8,
    label_related: []const u8,
    omitted_warnings: []const u8,

    // Diagnostic-kind summaries.
    kind_omitted_diagnostics: []const u8,
    kind_missing_proof_block: []const u8,
    kind_extra_proof_block: []const u8,
    kind_extra_proof_def: []const u8,
    kind_theorem_name_mismatch: []const u8,
    kind_missing_public_def_body: []const u8,
    kind_public_def_body_name_mismatch: []const u8,
    kind_public_def_body_header: []const u8,
    kind_unexpected_proof_def: []const u8,
    kind_unsupported_proof_def_annotation: []const u8,
    kind_duplicate_rule_name: []const u8,
    kind_statement_not_provable: []const u8,
    kind_statement_subexpr_sort: []const u8,
    kind_parse_assertion_fallback: []const u8,
    kind_binding_sort_mismatch: []const u8,
    kind_binding_boundness_mismatch: []const u8,
    kind_parse_binding_fallback: []const u8,
    kind_block_header_boundness: []const u8,
    kind_unknown_rule: []const u8,
    kind_unresolved_search_placeholder: []const u8,
    kind_rule_not_yet_available: []const u8,
    kind_unknown_binder_name: []const u8,
    kind_duplicate_binder_assignment: []const u8,
    kind_missing_binder_assignment: []const u8,
    kind_ref_count_mismatch: []const u8,
    kind_unknown_hypothesis_ref: []const u8,
    kind_ambiguous_hypothesis_ref: []const u8,
    kind_unknown_label: []const u8,
    kind_hypothesis_mismatch: []const u8,
    kind_conclusion_mismatch: []const u8,
    kind_duplicate_label: []const u8,
    kind_empty_proof_block: []const u8,
    kind_final_line_mismatch: []const u8,
    kind_unused_theorem_parameter: []const u8,
    kind_unused_definition_parameter: []const u8,
    defbody_dep_violation: []const u8,
    defbody_sort_mismatch: []const u8,
    defbody_fallback: []const u8,

    // Error summaries (compilerErrorSummary).
    err_BoundnessMismatch: []const u8,
    err_SortMismatch: []const u8,
    err_UnifyMismatch: []const u8,
    err_TermMismatch: []const u8,
    err_HypCountMismatch: []const u8,
    err_HoleTokenNameCollision: []const u8,
    err_BinderTokenCollision: []const u8,
    err_ResultDependencyOnDummy: []const u8,
    err_ArgDependencyOnDummy: []const u8,
    err_HoleyInferenceMismatch: []const u8,
    err_HoleConclusionMismatch: []const u8,
    err_AmbiguousAcuiMatch: []const u8,
    err_UnknownTheoremVariable: []const u8,
    err_DuplicateViewAnnotation: []const u8,
    err_InvalidViewAnnotation: []const u8,
    err_ViewHypCountMismatch: []const u8,
    err_ViewConclusionMismatch: []const u8,
    err_ViewHypothesisMismatch: []const u8,
    err_ViewBindingConflict: []const u8,
    err_RecoverWithoutView: []const u8,
    err_InvalidRecoverAnnotation: []const u8,
    err_UnknownRecoverBinder: []const u8,
    err_RecoverTargetNotRuleBinder: []const u8,
    err_RecoverSortMismatch: []const u8,
    err_RecoverHoleNotFound: []const u8,
    err_RecoverConflict: []const u8,
    err_RecoverStructureMismatch: []const u8,
    err_AbstractWithoutView: []const u8,
    err_InvalidAbstractAnnotation: []const u8,
    err_UnknownAbstractBinder: []const u8,
    err_AbstractTargetNotRuleBinder: []const u8,
    err_AbstractPlugSortMismatch: []const u8,
    err_AbstractNoPlugOccurrence: []const u8,
    err_AbstractConflict: []const u8,
    err_AbstractStructureMismatch: []const u8,
    err_UnknownTermAnnotation: []const u8,
    err_DummyAnnotationRemoved: []const u8,
    err_InvalidFreshAnnotation: []const u8,
    err_InvalidFreshenAnnotation: []const u8,
    err_InvalidAlphaAnnotation: []const u8,
    err_InvalidFallbackAnnotation: []const u8,
    err_DuplicateFallbackAnnotation: []const u8,
    err_UnknownFallbackRule: []const u8,
    err_InvalidAutoAnnotation: []const u8,
    err_EagerRuleDefersWitness: []const u8,
    err_InvalidTriggerAnnotation: []const u8,
    err_UnknownTriggerTerm: []const u8,
    err_UnknownTriggerBinder: []const u8,
    err_TriggerRuleHasHypotheses: []const u8,
    err_TriggerBinderNotGround: []const u8,
    err_TriggerSortMismatch: []const u8,
    err_TriggerBoundPosition: []const u8,
    err_FallbackCycle: []const u8,
    err_UnknownFreshBinder: []const u8,
    err_UnknownFreshenBinder: []const u8,
    err_UnknownAlphaBinder: []const u8,
    err_DuplicateFreshBinder: []const u8,
    err_DuplicateFreshenPair: []const u8,
    err_FreshRequiresBoundBinder: []const u8,
    err_FreshenTargetMustBeRegularBinder: []const u8,
    err_FreshenBlockerMustBeBoundBinder: []const u8,
    err_AlphaRequiresBoundBinders: []const u8,
    err_AlphaSortMismatch: []const u8,
    err_AlphaConclusionMustBeBinaryRelation: []const u8,
    err_AlphaConclusionUnsupported: []const u8,
    err_AlphaRuleHasHypotheses: []const u8,
    err_InvalidCongruenceAnnotation: []const u8,
    err_CongruenceBinderOrderMismatch: []const u8,
    err_CongruenceBinderMissingDeps: []const u8,
    err_RelationBundleBoundBinder: []const u8,
    err_InvalidConversionAnnotation: []const u8,
    err_InvalidDefConversionAnnotation: []const u8,
    err_ConversionTermNotDef: []const u8,
    err_ConversionDefUnfoldHiddenDummies: []const u8,
    err_DuplicateConversionAnnotation: []const u8,
    err_ConversionRuleHasHypotheses: []const u8,
    err_ConversionCommRuleShape: []const u8,
    err_ConversionAssocRuleShape: []const u8,
    err_ConversionAlphaRuleShape: []const u8,
    err_ConversionRoleBoundBinder: []const u8,
    err_ConversionRoleRelationHead: []const u8,
    err_DuplicateConversionRoleForHead: []const u8,
    err_ConversionConclusionNotRelation: []const u8,
    err_ConversionMissingRelation: []const u8,
    err_ConversionBareMatchSide: []const u8,
    err_ConversionBinderNotCovered: []const u8,
    err_InvalidComputeAnnotation: []const u8,
    err_DuplicateComputeAnnotation: []const u8,
    err_ComputeRuleHasHypotheses: []const u8,
    err_ComputeConclusionNotRelation: []const u8,
    err_ComputeMissingRelation: []const u8,
    err_ComputeBareMatchSide: []const u8,
    err_ComputeBinderNotCovered: []const u8,
    err_FreshStrictSort: []const u8,
    err_FreshFreeSort: []const u8,
    err_FreshNoAvailableVar: []const u8,
    err_HiddenWitnessNoAvailableVar: []const u8,
    err_NoAlphaRewriteAvailable: []const u8,
    err_AlphaRewriteSearchFailed: []const u8,
    err_DepViolation: []const u8,
    err_FreshenMissingRelation: []const u8,
    err_FreshenTransportFailed: []const u8,
    err_InvalidHoleAnnotation: []const u8,
    err_DuplicateHoleAnnotation: []const u8,
    err_DuplicateHoleToken: []const u8,
    err_InvalidVarsAnnotation: []const u8,
    err_VarsStrictSort: []const u8,
    err_VarsFreeSort: []const u8,
    err_DuplicateVarsToken: []const u8,
    err_VarsTokenCollision: []const u8,
    err_DependencySlotExhausted: []const u8,
    err_UnresolvedDummyWitness: []const u8,
    err_MissingCongruenceRule: []const u8,
    err_ExpectedIdentifier: []const u8,
    err_ExpectedNumber: []const u8,
    err_UnknownMathToken: []const u8,
    err_ExpectedMathToken: []const u8,
    err_ExpectedCloseParen: []const u8,
    err_TrailingMathTokens: []const u8,
    err_NotationMismatch: []const u8,
    err_AnonymousNotationBinder: []const u8,
    err_DummyNotationBinder: []const u8,
    err_InvalidNotationVariables: []const u8,
    err_PrecMismatch: []const u8,
    err_NotProvable: []const u8,
    err_ExpectedMathString: []const u8,
    err_PublicDefBodyMustBeHeaderless: []const u8,
    err_FillerBinderMustBeDummy: []const u8,
    err_DuplicateFillerBinderName: []const u8,
    err_TooManyBoundVars: []const u8,
    err_ExtraProofItem: []const u8,
    err_ExpectedBy: []const u8,
    err_ExpectedKeyword: []const u8,
    err_ExpectedString: []const u8,
    err_UnknownTerm: []const u8,
    err_UnknownSort: []const u8,
    err_UnknownVariable: []const u8,
    err_UnexpectedKeyword: []const u8,
    err_UnexpectedCharacter: []const u8,
    err_ExpectedLineEnd: []const u8,
    err_ExpectedBlockUnderline: []const u8,
    err_UnterminatedMathString: []const u8,
    err_UnterminatedString: []const u8,
    err_ExpectedDefEquals: []const u8,
    err_ExpectedProofBlock: []const u8,
    err_OutOfMemory: []const u8,
    err_UnexpectedInternalError: []const u8,
    err_UnknownDummyVar: []const u8,
    err_UnknownPlaceholder: []const u8,
    err_PlaceholderLeakage: []const u8,
    err_UnsolvedMetaLeakage: []const u8,
    err_Overflow: []const u8,
    err_TooManyTheoremExprs: []const u8,
    err_HoleNotConcrete: []const u8,
    err_HoleNotAllowedInTemplate: []const u8,
    err_TooManyCompilerRules: []const u8,
    err_TooManyCompilerTerms: []const u8,
    err_UnknownTemplateVariable: []const u8,
    err_InvalidExprUseCount: []const u8,
    err_TooManyTheoremVars: []const u8,
    err_ExpectedDefinitionBody: []const u8,
    err_ArgCountMismatch: []const u8,
    err_DummyHypothesisBinder: []const u8,
    err_DuplicateSort: []const u8,
    err_DuplicateTermName: []const u8,
    err_ExpectedFormula: []const u8,
    err_TooManySorts: []const u8,
    err_TooManyTerms: []const u8,
    err_UnexpectedHypothesisBinder: []const u8,
    err_UnexpectedTrailingInput: []const u8,
    err_UnexpectedEOF: []const u8,
    err_NumberOutOfRange: []const u8,
    err_MultiCharacterDelimiter: []const u8,
    err_InvalidNotationToken: []const u8,
    err_PrecedenceMismatch: []const u8,
    err_PrecedenceAssocMismatch: []const u8,
    err_NotationFirstTokenConflict: []const u8,
    err_ExpectedBinaryOperator: []const u8,
    err_ExpectedUnaryOperator: []const u8,
    err_InfixPrecOutOfRange: []const u8,
    err_CoercionCycle: []const u8,
    err_CoercionDiamond: []const u8,
    err_CoercionDiamondToProvable: []const u8,
    err_UnnamedRuleBinder: []const u8,

    // Note messages (renderNoteMessage).
    note_missing_semicolon_hint: []const u8,
    note_unknown_math_token_hint: []const u8,
    note_trailing_math_token_hint: []const u8,
    note_search_placeholder_meaning: []const u8,
    note_search_placeholder_unfinished: []const u8,
    note_rule_declared_later: []const u8,
    note_name_is_term_not_rule: []const u8,
    note_name_is_label_not_rule: []const u8,
    note_label_belongs_to_later_line: []const u8,
    note_def_body_result_sort: []const u8,
    note_def_body_checked_before_unify: []const u8,
    note_def_body_free_var_deps: []const u8,
    note_subexpression_sort_mismatch: []const u8,
    note_subexpression_needs_bound_var: []const u8,
    note_right_sort_but_needs_bound_var: []const u8,
    note_holey_fallback_exhausted: []const u8,
    note_visible_structure_mismatch: []const u8,
    note_unnamed_rule_var_two_values: []const u8,
    note_attempted_normalized_comparison: []const u8,
    note_boundary_mismatch_despite_unfolding: []const u8,
    note_boundary_mismatch_despite_normalization: []const u8,
    note_conclusion_replay_mismatch: []const u8,
    note_identical_positions_matched_differently: []const u8,
    note_no_rule_var_completion: []const u8,
    note_rule_requires_bound_var_here: []const u8,
    note_assignment_parses_as_sort: []const u8,
    note_statement_not_provable_sort: []const u8,
    note_premise_hypothesis_mismatch: []const u8,
    note_cited_premise_proves: []const u8,
    note_holey_unsolved_binder: []const u8,
    note_unsolved_binder_index: []const u8,
    note_conclusion_head_clash: []const u8,
    note_conclusion_head_clash_with_variable: []const u8,
    note_rule_var_two_values: []const u8,
    note_already_matched: []const u8,
    note_in_the_statement: []const u8,
    note_at_the_mismatch: []const u8,
    note_hole_sort_mismatch: []const u8,
    note_expected_expr: []const u8,
    note_actual_expr: []const u8,
    note_normalized_expected_expr: []const u8,
    note_normalized_actual_expr: []const u8,
    note_freshen_attempted_for_target: []const u8,
    note_freshen_blocker: []const u8,
    note_freshen_replacement: []const u8,
    note_freshen_still_depends_on_blocker: []const u8,
    note_freshen_no_longer_depends_on_blocker: []const u8,
    note_theorem_concludes: []const u8,
    note_last_line_proves: []const u8,
    note_explicit_bindings: []const u8,
    note_inferred_bindings_before_failure: []const u8,
    note_rule_requires_term_at_mismatch: []const u8,
    note_chosen_bindings: []const u8,
    note_alternative_bindings: []const u8,
    note_distinct_solutions_considered: []const u8,
    note_binder_resolved_to: []const u8,
    note_binding_sort_mismatch: []const u8,
    note_inference_path: []const u8,

    // Related-location labels.
    related_rule_declaration_here: []const u8,

    // Missing-congruence summaries.
    congr_missing_rule_for_term: []const u8,
    congr_missing_rule: []const u8,
    congr_changed_bound_arg_term: []const u8,
    congr_changed_bound_arg: []const u8,
    congr_changed_bound_arg_generic: []const u8,
    congr_missing_child_relation_term: []const u8,
    congr_missing_child_relation_arg: []const u8,
    congr_missing_child_relation: []const u8,
    congr_missing_child_proof_term: []const u8,
    congr_missing_child_proof_arg: []const u8,
    congr_missing_child_proof: []const u8,
    congr_missing_parent_relation_term: []const u8,
    congr_missing_parent_relation: []const u8,
    congr_malformed_rule_term: []const u8,
    congr_malformed_rule: []const u8,
    congr_unknown_term: []const u8,

    // Dependency-violation and omission summaries.
    omitted_diagnostics_count: []const u8,
    dep_bound_distinct: []const u8,
    dep_regular_mentions_bound: []const u8,
    dep_conflicting_binders: []const u8,
    dep_assignment: []const u8,
    detail_dep_violation_prefix: []const u8,
    detail_missing_congruence_prefix: []const u8,

    // Diagnostic context lines.
    ctx_theorem: []const u8,
    ctx_proof_block: []const u8,
    ctx_line: []const u8,
    ctx_rule: []const u8,
    ctx_name: []const u8,
    ctx_expected: []const u8,
    ctx_phase: []const u8,
    ctx_sort: []const u8,

    // Diagnostic detail lines.
    detail_token: []const u8,
    detail_did_you_mean: []const u8,
    detail_expected_char: []const u8,
    detail_missing_binder: []const u8,
    detail_inference_path: []const u8,
    detail_first_unsolved_binder: []const u8,
    detail_declared_sort: []const u8,
    detail_actual_sort: []const u8,
    detail_body_deps: []const u8,
    detail_hidden_binders: []const u8,
    detail_hypothesis_ref_name: []const u8,
    detail_hypothesis_ref_index: []const u8,
    detail_parameter: []const u8,

    // Inference-path names.
    path_strict_replay: []const u8,
    path_transparent_fallback: []const u8,
    path_normalized_session_fallback: []const u8,
    path_structural_solver: []const u8,
    path_holey_surface_match: []const u8,

    // Phase names.
    phase_parse: []const u8,
    phase_inference: []const u8,
    phase_theorem_application: []const u8,
    phase_freshen: []const u8,
    phase_normalization: []const u8,
    phase_final_reconciliation: []const u8,
};

pub const en: Strings = .{

    // Frontend framing labels.
    .label_error = "error",
    .label_warning = "warning",
    .label_note = "note",
    .label_related = "related",
    .omitted_warnings = "omitted {d} additional warning(s)",

    // Diagnostic-kind summaries.
    .kind_omitted_diagnostics = "additional diagnostics omitted",
    .kind_missing_proof_block = "missing proof block for theorem",
    .kind_extra_proof_block = "extra proof block with no matching theorem",
    .kind_extra_proof_def = "extra proof-side definition item",
    .kind_theorem_name_mismatch = "proof block name does not match the theorem",
    .kind_missing_public_def_body = "missing proof-side body for public definition",
    .kind_public_def_body_name_mismatch = "proof-side definition body targets a different public definition",
    .kind_public_def_body_header = "public definition body filler must not redeclare the signature (only dummy binders are allowed)",
    .kind_unexpected_proof_def = "unexpected proof-side definition item",
    .kind_unsupported_proof_def_annotation = "proof-side definition annotations are not supported yet",
    .kind_duplicate_rule_name = "duplicate rule name",
    .kind_statement_not_provable = "the statement is not of a provable sort",
    .kind_statement_subexpr_sort = "a subexpression of the statement has the wrong sort",
    .kind_parse_assertion_fallback = "could not parse proof line assertion",
    .kind_binding_sort_mismatch = "binder assignment has the wrong sort",
    .kind_binding_boundness_mismatch = "binder assignment must be a bound variable",
    .kind_parse_binding_fallback = "could not parse binder assignment",
    .kind_block_header_boundness = "the statement uses a compound expression where a bound variable is required",
    .kind_unknown_rule = "unknown rule in proof line",
    .kind_unresolved_search_placeholder = "proof line is justified by a search placeholder, not a completed proof",
    .kind_rule_not_yet_available = "rule is declared later and is not yet available here",
    .kind_unknown_binder_name = "unknown binder name in rule application",
    .kind_duplicate_binder_assignment = "duplicate binder assignment in rule application",
    .kind_missing_binder_assignment = "one of the rule's variables could not be determined from the statement and cited premises",
    .kind_ref_count_mismatch = "wrong number of references for rule application",
    .kind_unknown_hypothesis_ref = "unknown theorem hypothesis reference",
    .kind_ambiguous_hypothesis_ref = "hypothesis name matches more than one hypothesis",
    .kind_unknown_label = "unknown proof line label",
    .kind_hypothesis_mismatch = "a cited premise does not match the hypothesis the rule expects there",
    .kind_conclusion_mismatch = "proof line assertion does not match the rule conclusion",
    .kind_duplicate_label = "duplicate proof line label",
    .kind_empty_proof_block = "proof block is empty",
    .kind_final_line_mismatch = "last proof line does not prove the theorem conclusion",
    .kind_unused_theorem_parameter = "theorem parameter is unused; if it is only needed during proofs, use @vars and an explicit theorem-local dummy instead",
    .kind_unused_definition_parameter = "definition parameter is unused; remove it if it is not part of the definition",
    .defbody_dep_violation = "definition body has free variables that the result type does not declare",
    .defbody_sort_mismatch = "definition body sort does not match the declared result sort",
    .defbody_fallback = "definition body does not satisfy the declared result",

    // Error summaries (compilerErrorSummary).
    .err_BoundnessMismatch = "binding does not satisfy the rule's bound-variable constraint",
    .err_SortMismatch = "binding does not satisfy the rule's sort constraint",
    .err_UnifyMismatch = "the statement and cited premises could not be matched against this rule",
    .err_TermMismatch = "the statement or a cited premise does not have the shape this rule requires",
    .err_HypCountMismatch = "the number of cited premises does not match the number of hypotheses this rule has",
    .err_HoleTokenNameCollision = "name conflicts with a proof hole token",
    .err_BinderTokenCollision = "binder name conflicts with a declared notation token",
    .err_ResultDependencyOnDummy = "a result type may only depend on bound variables from the argument list, not hidden binders",
    .err_ArgDependencyOnDummy = "an argument type may only depend on bound variables from the argument list, not hidden binders",
    .err_HoleyInferenceMismatch = "the visible parts of the statement do not match what this rule proves",
    .err_HoleConclusionMismatch = "the visible parts of the statement do not match the rule's conclusion",
    .err_AmbiguousAcuiMatch = "the omitted parts of this rule application can be completed in more than one way",
    .err_UnknownTheoremVariable = "binding refers to a theorem variable that is not in scope",
    .err_DuplicateViewAnnotation = "multiple @view annotations were attached to one rule",
    .err_InvalidViewAnnotation = "could not parse @view annotation",
    .err_ViewHypCountMismatch = "@view hypothesis count does not match the rule",
    .err_ViewConclusionMismatch = "@view conclusion does not match the proof line assertion",
    .err_ViewHypothesisMismatch = "@view hypotheses do not match the cited refs",
    .err_ViewBindingConflict = "@view inference conflicts with an explicit binding",
    .err_RecoverWithoutView = "@recover requires a preceding @view on the same rule",
    .err_InvalidRecoverAnnotation = "@recover expects four binder names: target source pattern hole",
    .err_UnknownRecoverBinder = "@recover refers to a binder name not present in the view",
    .err_RecoverTargetNotRuleBinder = "@recover target must be a real rule binder",
    .err_RecoverSortMismatch = "@recover target and hole binders must have the same sort or sorts that share a coercion target",
    .err_RecoverHoleNotFound = "@recover could not find the hole binder in the pattern expr",
    .err_RecoverConflict = "@recover found inconsistent candidates for the target binder",
    .err_RecoverStructureMismatch = "@recover source expr does not match the pattern structure",
    .err_AbstractWithoutView = "@abstract requires a preceding @view on the same rule",
    .err_InvalidAbstractAnnotation = "@abstract expects six binder names: target left right hole left_plug right_plug",
    .err_UnknownAbstractBinder = "@abstract refers to a binder name not present in the view",
    .err_AbstractTargetNotRuleBinder = "@abstract target must be a real rule binder",
    .err_AbstractPlugSortMismatch = "@abstract hole and plug binders must have the same sort or sorts that share a coercion target",
    .err_AbstractNoPlugOccurrence = "@abstract could not find the plug pair in the source exprs",
    .err_AbstractConflict = "@abstract found a context that conflicts with the target binder",
    .err_AbstractStructureMismatch = "@abstract source exprs do not match outside the plug pair",
    .err_UnknownTermAnnotation = "unknown term-level annotation",
    .err_DummyAnnotationRemoved = "@dummy was removed; use @fresh instead",
    .err_InvalidFreshAnnotation = "@fresh expects exactly one real rule binder name",
    .err_InvalidFreshenAnnotation = "@freshen expects two binder names: target blocker",
    .err_InvalidAlphaAnnotation = "@alpha expects two bound binder names: old new",
    .err_InvalidFallbackAnnotation = "@fallback expects exactly one rule name",
    .err_DuplicateFallbackAnnotation = "multiple @fallback annotations were attached to one rule",
    .err_UnknownFallbackRule = "@fallback refers to a rule that is not available here",
    .err_InvalidAutoAnnotation = "@auto expects one mode: forward, backward, eager [PRIORITY >= 1], or trigger PATTERN",
    .err_EagerRuleDefersWitness = "@auto eager rule must not defer a witness: every hypothesis binder must appear in the conclusion",
    .err_InvalidTriggerAnnotation = "@auto trigger expects one parenthesized prefix pattern: (term binder-or-_ ...)",
    .err_UnknownTriggerTerm = "@auto trigger names a term that is not available here",
    .err_UnknownTriggerBinder = "@auto trigger refers to a binder that is not on the rule",
    .err_TriggerRuleHasHypotheses = "@auto trigger rule must not have hypotheses",
    .err_TriggerBinderNotGround = "@auto trigger must name every rule binder that cannot default to an ACUI unit",
    .err_TriggerSortMismatch = "@auto trigger pattern position has the wrong sort",
    .err_TriggerBoundPosition = "@auto trigger bound argument positions admit only _",
    .err_FallbackCycle = "@fallback chain contains a cycle",
    .err_UnknownFreshBinder = "@fresh target must be a real rule binder",
    .err_UnknownFreshenBinder = "@freshen refers to a binder that is not on the rule",
    .err_UnknownAlphaBinder = "@alpha refers to a binder that is not on the rule",
    .err_DuplicateFreshBinder = "multiple @fresh annotations were attached to one rule binder",
    .err_DuplicateFreshenPair = "multiple identical @freshen annotations were attached to one rule",
    .err_FreshRequiresBoundBinder = "@fresh target must be a bound rule binder",
    .err_FreshenTargetMustBeRegularBinder = "@freshen target must be a regular rule binder",
    .err_FreshenBlockerMustBeBoundBinder = "@freshen blocker must be a bound rule binder",
    .err_AlphaRequiresBoundBinders = "@alpha binders must both be bound rule binders",
    .err_AlphaSortMismatch = "@alpha binders must have the same sort",
    .err_AlphaConclusionMustBeBinaryRelation = "@alpha rule conclusion must be a binary relation",
    .err_AlphaConclusionUnsupported = "@alpha rule left-hand side must be a term application",
    .err_AlphaRuleHasHypotheses = "@alpha rule must not have hypotheses",
    .err_InvalidCongruenceAnnotation = "@congr rule does not have the expected congruence shape",
    .err_CongruenceBinderOrderMismatch = "@congr binders must be ordered old₀ new₀ old₁ new₁ ...",
    .err_CongruenceBinderMissingDeps = "@congr old/new binders must declare every dependency the head term's argument permits (e.g. (p q: wff x))",
    .err_RelationBundleBoundBinder = "@relation bundle rules (refl/trans/symm/transport) must not have bound binders",
    .err_InvalidConversionAnnotation = "@conversion expects one token: ltr, rtl, both, assoc, or comm",
    .err_InvalidDefConversionAnnotation = "@conversion on a definition expects one token: unfold, fold, or both",
    .err_ConversionTermNotDef = "@conversion on a term requires a definition with a visible definiens",
    .err_ConversionDefUnfoldHiddenDummies = "@conversion unfold/both cannot enroll a definition with hidden dummy binders: unfolding would have to invent a dummy witness at every match; only fold is legal here",
    .err_DuplicateConversionAnnotation = "multiple @conversion annotations were attached to one rule",
    .err_ConversionRuleHasHypotheses = "@conversion rule must not have hypotheses",
    .err_ConversionCommRuleShape = "@conversion comm requires the conclusion rel(t(a, b), t(b, a)) over exactly two distinct binders",
    .err_ConversionAssocRuleShape = "@conversion assoc requires the conclusion rel(t(t(a, b), c), t(a, t(b, c))) (either orientation) over exactly three distinct binders",
    .err_ConversionAlphaRuleShape = "@conversion alpha requires both conclusion sides to share a head with exactly one renamed bound binder at a bound argument position of that head, fresh on the right and of the same sort",
    .err_ConversionRoleBoundBinder = "@conversion assoc/comm rules must not have bound binders",
    .err_ConversionRoleRelationHead = "@conversion assoc/comm cannot certify a registered @relation term: relation applications must stay plain so local equations can be cited directly",
    .err_DuplicateConversionRoleForHead = "another @conversion rule already certifies this law for the same operator",
    .err_ConversionConclusionNotRelation = "@conversion rule conclusion must have the shape rel(lhs, rhs)",
    .err_ConversionMissingRelation = "@conversion rule conclusion head must be the registered @relation term for its operand sort",
    .err_ConversionBareMatchSide = "@conversion match side must be a term application, not a bare binder",
    .err_ConversionBinderNotCovered = "@conversion match side must bind every binder the instantiate side uses",
    .err_InvalidComputeAnnotation = "@compute expects one token: ltr or rtl",
    .err_DuplicateComputeAnnotation = "this rule is already enrolled for conversion? (one @compute/@conversion enrollment per rule)",
    .err_ComputeRuleHasHypotheses = "@compute rule must not have hypotheses",
    .err_ComputeConclusionNotRelation = "@compute rule conclusion must have the shape rel(lhs, rhs)",
    .err_ComputeMissingRelation = "@compute rule conclusion head must be the registered @relation term for its operand sort",
    .err_ComputeBareMatchSide = "@compute match side must be a term application, not a bare binder",
    .err_ComputeBinderNotCovered = "@compute match side must bind every binder the instantiate side uses",
    .err_FreshStrictSort = "@fresh cannot target a binder in a strict sort",
    .err_FreshFreeSort = "@fresh cannot target a binder in a free sort",
    .err_FreshNoAvailableVar = "@fresh could not find an available @vars token",
    .err_HiddenWitnessNoAvailableVar = "hidden def witness needed a fresh @vars token, but none was available",
    .err_NoAlphaRewriteAvailable = "no matching @alpha rule was available for this @freshen step",
    .err_AlphaRewriteSearchFailed = "the available @alpha rules did not remove the blocker dependency",
    .err_DepViolation = "binder assignments violate the rule's dependency constraints",
    .err_FreshenMissingRelation = "freshening needs a registered relation on the affected sort",
    .err_FreshenTransportFailed = "freshening could not lift the alpha rewrite through the rule formula",
    .err_InvalidHoleAnnotation = "@hole expects exactly one raw math token",
    .err_DuplicateHoleAnnotation = "multiple @hole annotations were attached to one sort",
    .err_DuplicateHoleToken = "duplicate @hole token across sorts",
    .err_InvalidVarsAnnotation = "@vars expects one or more raw math tokens",
    .err_VarsStrictSort = "@vars cannot be used on a strict sort",
    .err_VarsFreeSort = "@vars cannot be used on a free sort",
    .err_DuplicateVarsToken = "duplicate @vars token across sorts",
    .err_VarsTokenCollision = "@vars token collides with an existing term, notation, or formula marker",
    .err_DependencySlotExhausted = "theorem exceeded the 55 tracked bound-variable dependency slots",
    .err_UnresolvedDummyWitness = "matched rule through hidden def structure, but omitted binders contain unresolved hidden-dummy witnesses",
    .err_MissingCongruenceRule = "missing congruence rule needed for normalization",
    .err_ExpectedIdentifier = "expected identifier",
    .err_ExpectedNumber = "expected number",
    .err_UnknownMathToken = "unknown token in math string",
    .err_ExpectedMathToken = "expected token in math string",
    .err_ExpectedCloseParen = "expected closing parenthesis in math string",
    .err_TrailingMathTokens = "unexpected trailing tokens in math string",
    .err_NotationMismatch = "token sequence does not match declared notation",
    .err_AnonymousNotationBinder = "anonymous binders are not permitted in notation declarations",
    .err_DummyNotationBinder = "dummy binders are not permitted in notation declarations",
    .err_InvalidNotationVariables = "notation must mention each declared argument exactly once",
    .err_PrecMismatch = "operator precedence does not allow this parse",
    .err_NotProvable = "math string does not have a provable sort",
    .err_ExpectedMathString = "expected $...$ math string",
    .err_PublicDefBodyMustBeHeaderless = "public definition body filler may declare only dummy binders before `=`",
    .err_FillerBinderMustBeDummy = "public definition body filler binders must be hidden dummies like (.x: s)",
    .err_DuplicateFillerBinderName = "filler dummy name is already bound by the definition",
    .err_TooManyBoundVars = "a declaration may bind at most 55 variables (bound binders and hidden dummies together)",
    .err_ExtraProofItem = "extra proof item with no matching declaration",
    .err_ExpectedBy = "expected 'by' after the proof line's statement",
    .err_ExpectedKeyword = "expected keyword",
    .err_ExpectedString = "expected quoted string",
    .err_UnknownTerm = "unknown term",
    .err_UnknownSort = "unknown sort",
    .err_UnknownVariable = "unknown variable",
    .err_UnexpectedKeyword = "unexpected keyword",
    .err_UnexpectedCharacter = "unexpected character",
    .err_ExpectedLineEnd = "expected end of line",
    .err_ExpectedBlockUnderline = "expected underline after proof block header",
    .err_UnterminatedMathString = "unterminated $...$ math string",
    .err_UnterminatedString = "unterminated string",
    .err_ExpectedDefEquals = "expected '=' in the proof-side definition body",
    .err_ExpectedProofBlock = "expected a proof block",
    .err_OutOfMemory = "the compiler ran out of memory",
    .err_UnexpectedInternalError = "unexpected internal error; please report this",
    .err_UnknownDummyVar = "internal error: unknown dummy variable; please report this",
    .err_UnknownPlaceholder = "internal error: unknown placeholder; please report this",
    .err_PlaceholderLeakage = "an unresolved search placeholder remains in this proof",
    .err_UnsolvedMetaLeakage = "an unsolved metavariable remains in this proof",
    .err_Overflow = "an internal limit overflowed; the theorem may be too large",
    .err_TooManyTheoremExprs = "theorem is too large (internal expression limit exceeded)",
    .err_HoleNotConcrete = "a proof hole is not allowed here",
    .err_HoleNotAllowedInTemplate = "a proof hole is not allowed in a rule statement",
    .err_TooManyCompilerRules = "too many rules declared",
    .err_TooManyCompilerTerms = "too many terms declared (compiler limit)",
    .err_UnknownTemplateVariable = "internal error: unknown template variable; please report this",
    .err_InvalidExprUseCount = "internal error in proof emission; please report this",
    .err_TooManyTheoremVars = "theorem has too many variables",
    .err_ExpectedDefinitionBody = "definition has no body",
    .err_ArgCountMismatch = "wrong number of arguments for term",
    .err_DummyHypothesisBinder = "hypothesis binders cannot be dummies",
    .err_DuplicateSort = "duplicate sort name",
    .err_DuplicateTermName = "duplicate term or definition name",
    .err_ExpectedFormula = "expected a formula",
    .err_TooManySorts = "too many sorts declared",
    .err_TooManyTerms = "too many terms declared",
    .err_UnexpectedHypothesisBinder = "hypothesis binders are not allowed in this declaration",
    .err_UnexpectedTrailingInput = "unexpected input after the end of the statement",
    .err_UnexpectedEOF = "unexpected end of file",
    .err_NumberOutOfRange = "number is too large (at most 65535)",
    .err_MultiCharacterDelimiter = "delimiters must be single characters",
    .err_InvalidNotationToken = "'(' and ')' cannot be used as notation tokens",
    .err_PrecedenceMismatch = "token was already declared with a different precedence",
    .err_PrecedenceAssocMismatch = "this precedence level was already declared with the opposite associativity",
    .err_NotationFirstTokenConflict = "a notation's first token cannot also be a prefix or infix token",
    .err_ExpectedBinaryOperator = "infix notation requires a term with exactly two arguments",
    .err_ExpectedUnaryOperator = "prefix notation requires a term with exactly one argument",
    .err_InfixPrecOutOfRange = "infix operator precedence is out of range",
    .err_CoercionCycle = "coercion would create a cycle between sorts",
    .err_CoercionDiamond = "coercion would create a second route between two sorts (coercion paths must be unique)",
    .err_CoercionDiamondToProvable = "coercion would create a second route to a provable sort",
    .err_UnnamedRuleBinder = "binder assignment targets an unnamed rule binder",

    // Note messages (renderNoteMessage).
    .note_missing_semicolon_hint = "usually a missing ';' at the end of the declaration before this point",
    .note_unknown_math_token_hint = "the token is not a variable of this theorem, nor a term or notation of the theory",
    .note_trailing_math_token_hint = "the expression to the left parses on its own; this token is not a notation that can extend it",
    .note_search_placeholder_meaning = "search placeholders (auto?, exact?, apply?, conversion?) stand for a search that runs in the editor and is replaced by the proof it finds",
    .note_search_placeholder_unfinished = "the compiler only checks finished proofs; this search has not produced one yet",
    .note_rule_declared_later = "rule is declared later in the mm0 file",
    .note_name_is_term_not_rule = "this name is a term or definition; it can appear inside formulas but cannot justify a proof line",
    .note_name_is_label_not_rule = "this name is a proof line label, not a rule; earlier lines are cited as premises in the brackets after a rule",
    .note_label_belongs_to_later_line = "this label belongs to a later line; a line can only cite the lines above it",
    .note_def_body_result_sort = "the definition body must already have the declared result sort",
    .note_def_body_checked_before_unify = "definition bodies are checked before the def unify stream runs",
    .note_def_body_free_var_deps = "every free variable of the body must be declared as a dependency of the result type",
    .note_subexpression_sort_mismatch = "a subexpression here is used where a different sort is expected",
    .note_subexpression_needs_bound_var = "a position inside this expression requires a single bound variable",
    .note_right_sort_but_needs_bound_var = "the assignment parses with the right sort, but this binder requires a single bound variable",
    .note_holey_fallback_exhausted = "fallback chain exhausted for holey assertion; showing first candidate failure",
    .note_visible_structure_mismatch = "the visible parts of the statement do not match the rule's conclusion",
    .note_unnamed_rule_var_two_values = "one rule variable would need two different values",
    .note_attempted_normalized_comparison = "attempted normalized comparison",
    .note_boundary_mismatch_despite_unfolding = "the two do not match, even with definitions unfolded",
    .note_boundary_mismatch_despite_normalization = "nor after normalization",
    .note_conclusion_replay_mismatch = "the statement does not match the rule's conclusion",
    .note_identical_positions_matched_differently = "two positions the rule requires to be identical matched different expressions",
    .note_no_rule_var_completion = "no way of filling in the rule's variables makes them match",
    .note_rule_requires_bound_var_here = "the rule requires a single bound variable here",
    .note_assignment_parses_as_sort = "the assignment parses, but as sort '{s}'; this binder expects sort '{s}'",
    .note_statement_not_provable_sort = "the statement parses, but as sort '{s}', which is not a provable sort",
    .note_premise_hypothesis_mismatch = "cited premise {0d} does not match hypothesis {0d} of the rule",
    .note_cited_premise_proves = "the cited premise proves: {s}",
    .note_holey_unsolved_binder = "holey assertion left binder {s} unsolved",
    .note_unsolved_binder_index = "unsolved binder index: {d}",
    .note_conclusion_head_clash = "the rule's conclusion has '{s}' where the statement has '{s}'",
    .note_conclusion_head_clash_with_variable = "the rule's conclusion has '{s}' where the statement has a variable",
    .note_rule_var_two_values = "rule variable {s} would need two different values",
    .note_already_matched = "already matched: {s}",
    .note_in_the_statement = "in the statement: {s}",
    .note_at_the_mismatch = "at the mismatch: {s}",
    .note_hole_sort_mismatch = "hole {s} expected sort {s} but matched {s}",
    .note_expected_expr = "expected: {s}",
    .note_actual_expr = "actual: {s}",
    .note_normalized_expected_expr = "normalized expected: {s}",
    .note_normalized_actual_expr = "normalized actual: {s}",
    .note_freshen_attempted_for_target = "attempted @freshen for target binder {s}",
    .note_freshen_blocker = "freshen blocker binder: {s}",
    .note_freshen_replacement = "chosen replacement binder: {s}",
    .note_freshen_still_depends_on_blocker = "rewritten target still depends on blocker binder {s}",
    .note_freshen_no_longer_depends_on_blocker = "rewritten target no longer depends on blocker binder {s}",
    .note_theorem_concludes = "the theorem concludes: {s}",
    .note_last_line_proves = "the last line proves: {s}",
    .note_explicit_bindings = "explicit bindings: {s}",
    .note_inferred_bindings_before_failure = "inferred bindings before failure: {s}",
    .note_rule_requires_term_at_mismatch = "the rule requires '{s}' at the mismatch, but found: {s}",
    .note_chosen_bindings = "chosen bindings: {s}",
    .note_alternative_bindings = "alternative bindings: {s}",
    .note_distinct_solutions_considered = "distinct solutions considered: {d}",
    .note_binder_resolved_to = "this binder was resolved to: {s}",
    .note_binding_sort_mismatch = "it has sort '{s}', but the rule expects sort '{s}' here",
    .note_inference_path = "inference path: {s}",

    // Related-location labels.
    .related_rule_declaration_here = "rule declaration is here",

    // Missing-congruence summaries.
    .congr_missing_rule_for_term = "missing @congr for term {s}",
    .congr_missing_rule = "missing @congr rule",
    .congr_changed_bound_arg_term = "bound argument {0d} of term {1s} changed during normalization",
    .congr_changed_bound_arg = "bound argument {d} changed during normalization",
    .congr_changed_bound_arg_generic = "bound argument changed during normalization",
    .congr_missing_child_relation_term = "missing relation for argument {0d} of term {1s}",
    .congr_missing_child_relation_arg = "missing relation for argument {d}",
    .congr_missing_child_relation = "missing child relation",
    .congr_missing_child_proof_term = "argument {0d} of term {1s} changed without a congruence proof",
    .congr_missing_child_proof_arg = "argument {d} changed without a congruence proof",
    .congr_missing_child_proof = "argument changed without a congruence proof",
    .congr_missing_parent_relation_term = "missing parent relation for term {s}",
    .congr_missing_parent_relation = "missing parent relation",
    .congr_malformed_rule_term = "malformed @congr rule for term {s}",
    .congr_malformed_rule = "malformed @congr rule",
    .congr_unknown_term = "normalization used an unknown term",

    // Dependency-violation and omission summaries.
    .omitted_diagnostics_count = "{d} more diagnostics omitted",
    .dep_bound_distinct = "bound variables {0s} and {1s} must be assigned distinct variables",
    .dep_regular_mentions_bound = "the rule does not allow {0s} to mention the variable assigned to {1s}",
    .dep_conflicting_binders = "conflicting binders {0s} and {1s}",
    .dep_assignment = "{0s} was assigned: {1s}",
    .detail_dep_violation_prefix = "dependency violation: ",
    .detail_missing_congruence_prefix = "missing congruence: ",

    // Diagnostic context lines.
    .ctx_theorem = "theorem: {s}",
    .ctx_proof_block = "proof block: {s}",
    .ctx_line = "line: {s}",
    .ctx_rule = "rule: {s}",
    .ctx_name = "name: {s}",
    .ctx_expected = "expected: {s}",
    .ctx_phase = "phase: {s}",
    .ctx_sort = "sort: {s}",

    // Diagnostic detail lines.
    .detail_token = "token: {s}",
    .detail_did_you_mean = "did you mean: {s}",
    .detail_expected_char = "expected: '{c}'",
    .detail_missing_binder = "missing binder: {s}",
    .detail_inference_path = "inference path: {s}",
    .detail_first_unsolved_binder = "first unsolved binder: {s}",
    .detail_declared_sort = "declared sort: {s}",
    .detail_actual_sort = "actual sort: {s}",
    .detail_body_deps = "body deps: 0x{x}",
    .detail_hidden_binders = "hidden binders: {d}",
    .detail_hypothesis_ref_name = "hypothesis ref: #{s}",
    .detail_hypothesis_ref_index = "hypothesis ref: #{d}",
    .detail_parameter = "parameter: {s}",

    // Inference-path names.
    .path_strict_replay = "exact match",
    .path_transparent_fallback = "matching with definitions unfolded",
    .path_normalized_session_fallback = "matching after normalization",
    .path_structural_solver = "structural matching",
    .path_holey_surface_match = "holey assertion match",

    // Phase names.
    .phase_parse = "parse",
    .phase_inference = "inference",
    .phase_theorem_application = "theorem application",
    .phase_freshen = "freshen",
    .phase_normalization = "normalization",
    .phase_final_reconciliation = "final reconciliation",
};

pub const de: Strings = .{

    // Frontend framing labels.
    .label_error = "Fehler",
    .label_warning = "Warnung",
    .label_note = "Hinweis",
    .label_related = "siehe",
    .omitted_warnings = "{d} weitere Warnung(en) ausgelassen",

    // Diagnostic-kind summaries.
    .kind_omitted_diagnostics = "weitere Diagnosen ausgelassen",
    .kind_missing_proof_block = "fehlender Beweisblock für das Theorem",
    .kind_extra_proof_block = "überzähliger Beweisblock ohne zugehöriges Theorem",
    .kind_extra_proof_def = "überzähliges beweisseitiges Definitionselement",
    .kind_theorem_name_mismatch = "der Name des Beweisblocks stimmt nicht mit dem Theorem überein",
    .kind_missing_public_def_body = "fehlender beweisseitiger Rumpf für eine öffentliche Definition",
    .kind_public_def_body_name_mismatch = "der beweisseitige Definitionsrumpf gehört zu einer anderen öffentlichen Definition",
    .kind_public_def_body_header = "die Ergänzung eines öffentlichen Definitionsrumpfs darf die Signatur nicht wiederholen (nur Dummy-Binder sind erlaubt)",
    .kind_unexpected_proof_def = "unerwartetes beweisseitiges Definitionselement",
    .kind_unsupported_proof_def_annotation = "beweisseitige Definitions-Annotationen werden noch nicht unterstützt",
    .kind_duplicate_rule_name = "doppelter Regelname",
    .kind_statement_not_provable = "die Aussage hat keine beweisbare Sorte",
    .kind_statement_subexpr_sort = "ein Teilausdruck der Aussage hat die falsche Sorte",
    .kind_parse_assertion_fallback = "die Aussage der Beweiszeile konnte nicht geparst werden",
    .kind_binding_sort_mismatch = "die Binderzuweisung hat die falsche Sorte",
    .kind_binding_boundness_mismatch = "die Binderzuweisung muss eine gebundene Variable sein",
    .kind_parse_binding_fallback = "die Binderzuweisung konnte nicht geparst werden",
    .kind_block_header_boundness = "die Aussage verwendet einen zusammengesetzten Ausdruck, wo eine gebundene Variable verlangt ist",
    .kind_unknown_rule = "unbekannte Regel in der Beweiszeile",
    .kind_unresolved_search_placeholder = "die Beweiszeile beruft sich auf einen Suchplatzhalter, nicht auf einen fertigen Beweis",
    .kind_rule_not_yet_available = "die Regel wird erst später deklariert und ist hier noch nicht verfügbar",
    .kind_unknown_binder_name = "unbekannter Bindername in der Regelanwendung",
    .kind_duplicate_binder_assignment = "doppelte Binderzuweisung in der Regelanwendung",
    .kind_missing_binder_assignment = "eine der Regelvariablen ließ sich nicht aus der Aussage und den zitierten Prämissen bestimmen",
    .kind_ref_count_mismatch = "falsche Anzahl von Referenzen für die Regelanwendung",
    .kind_unknown_hypothesis_ref = "unbekannte Referenz auf eine Theorem-Hypothese",
    .kind_ambiguous_hypothesis_ref = "der Hypothesenname passt auf mehr als eine Hypothese",
    .kind_unknown_label = "unbekanntes Beweiszeilen-Label",
    .kind_hypothesis_mismatch = "eine zitierte Prämisse passt nicht zu der Hypothese, die die Regel an dieser Stelle erwartet",
    .kind_conclusion_mismatch = "die Aussage der Beweiszeile stimmt nicht mit der Konklusion der Regel überein",
    .kind_duplicate_label = "doppeltes Beweiszeilen-Label",
    .kind_empty_proof_block = "der Beweisblock ist leer",
    .kind_final_line_mismatch = "die letzte Beweiszeile beweist nicht die Konklusion des Theorems",
    .kind_unused_theorem_parameter = "der Theorem-Parameter wird nicht verwendet; wird er nur in Beweisen gebraucht, verwenden Sie stattdessen @vars und einen expliziten theoremlokalen Dummy",
    .kind_unused_definition_parameter = "der Definitionsparameter wird nicht verwendet; entfernen Sie ihn, wenn er nicht Teil der Definition ist",
    .defbody_dep_violation = "der Definitionsrumpf hat freie Variablen, die der Ergebnistyp nicht deklariert",
    .defbody_sort_mismatch = "die Sorte des Definitionsrumpfs stimmt nicht mit der deklarierten Ergebnissorte überein",
    .defbody_fallback = "der Definitionsrumpf erfüllt das deklarierte Ergebnis nicht",

    // Error summaries (compilerErrorSummary).
    .err_BoundnessMismatch = "die Zuweisung erfüllt die Anforderung der Regel an gebundene Variablen nicht",
    .err_SortMismatch = "die Zuweisung erfüllt die Sortenanforderung der Regel nicht",
    .err_UnifyMismatch = "die Aussage und die zitierten Prämissen passen nicht auf diese Regel",
    .err_TermMismatch = "die Aussage oder eine zitierte Prämisse hat nicht die Form, die diese Regel verlangt",
    .err_HypCountMismatch = "die Anzahl der zitierten Prämissen stimmt nicht mit der Anzahl der Hypothesen dieser Regel überein",
    .err_HoleTokenNameCollision = "der Name kollidiert mit einem Beweisloch-Token",
    .err_BinderTokenCollision = "der Bindername kollidiert mit einem deklarierten Notations-Token",
    .err_ResultDependencyOnDummy = "ein Ergebnistyp darf nur von gebundenen Variablen der Argumentliste abhängen, nicht von verborgenen Bindern",
    .err_ArgDependencyOnDummy = "ein Argumenttyp darf nur von gebundenen Variablen der Argumentliste abhängen, nicht von verborgenen Bindern",
    .err_HoleyInferenceMismatch = "die sichtbaren Teile der Aussage passen nicht zu dem, was diese Regel beweist",
    .err_HoleConclusionMismatch = "die sichtbaren Teile der Aussage stimmen nicht mit der Konklusion der Regel überein",
    .err_AmbiguousAcuiMatch = "die ausgelassenen Teile dieser Regelanwendung lassen sich auf mehr als eine Weise vervollständigen",
    .err_UnknownTheoremVariable = "die Zuweisung verweist auf eine Theoremvariable, die hier nicht im Gültigkeitsbereich ist",
    .err_DuplicateViewAnnotation = "an einer Regel sind mehrere @view-Annotationen angebracht",
    .err_InvalidViewAnnotation = "die @view-Annotation konnte nicht geparst werden",
    .err_ViewHypCountMismatch = "die Hypothesenzahl der @view stimmt nicht mit der Regel überein",
    .err_ViewConclusionMismatch = "die @view-Konklusion stimmt nicht mit der Aussage der Beweiszeile überein",
    .err_ViewHypothesisMismatch = "die @view-Hypothesen passen nicht zu den zitierten Referenzen",
    .err_ViewBindingConflict = "die @view-Inferenz steht im Widerspruch zu einer expliziten Zuweisung",
    .err_RecoverWithoutView = "@recover erfordert ein vorangehendes @view an derselben Regel",
    .err_InvalidRecoverAnnotation = "@recover erwartet vier Bindernamen: target source pattern hole",
    .err_UnknownRecoverBinder = "@recover verweist auf einen Bindernamen, der in der View nicht vorkommt",
    .err_RecoverTargetNotRuleBinder = "das @recover-Ziel muss ein echter Regelbinder sein",
    .err_RecoverSortMismatch = "Ziel- und Loch-Binder von @recover müssen dieselbe Sorte oder Sorten mit gemeinsamem Koerzionsziel haben",
    .err_RecoverHoleNotFound = "@recover konnte den Loch-Binder im Musterausdruck nicht finden",
    .err_RecoverConflict = "@recover fand widersprüchliche Kandidaten für den Ziel-Binder",
    .err_RecoverStructureMismatch = "der @recover-Quellausdruck passt nicht auf die Struktur des Musters",
    .err_AbstractWithoutView = "@abstract erfordert ein vorangehendes @view an derselben Regel",
    .err_InvalidAbstractAnnotation = "@abstract erwartet sechs Bindernamen: target left right hole left_plug right_plug",
    .err_UnknownAbstractBinder = "@abstract verweist auf einen Bindernamen, der in der View nicht vorkommt",
    .err_AbstractTargetNotRuleBinder = "das @abstract-Ziel muss ein echter Regelbinder sein",
    .err_AbstractPlugSortMismatch = "Loch- und Einsatz-Binder von @abstract müssen dieselbe Sorte oder Sorten mit gemeinsamem Koerzionsziel haben",
    .err_AbstractNoPlugOccurrence = "@abstract konnte das Einsatzpaar in den Quellausdrücken nicht finden",
    .err_AbstractConflict = "@abstract fand einen Kontext, der dem Ziel-Binder widerspricht",
    .err_AbstractStructureMismatch = "die @abstract-Quellausdrücke stimmen außerhalb des Einsatzpaares nicht überein",
    .err_UnknownTermAnnotation = "unbekannte Annotation auf Term-Ebene",
    .err_DummyAnnotationRemoved = "@dummy wurde entfernt; verwenden Sie stattdessen @fresh",
    .err_InvalidFreshAnnotation = "@fresh erwartet genau einen Namen eines echten Regelbinders",
    .err_InvalidFreshenAnnotation = "@freshen erwartet zwei Bindernamen: target blocker",
    .err_InvalidAlphaAnnotation = "@alpha erwartet zwei gebundene Bindernamen: old new",
    .err_InvalidFallbackAnnotation = "@fallback erwartet genau einen Regelnamen",
    .err_DuplicateFallbackAnnotation = "an einer Regel sind mehrere @fallback-Annotationen angebracht",
    .err_UnknownFallbackRule = "@fallback verweist auf eine Regel, die hier nicht verfügbar ist",
    .err_InvalidAutoAnnotation = "@auto erwartet einen Modus: forward, backward, eager [PRIORITÄT >= 1] oder trigger MUSTER",
    .err_EagerRuleDefersWitness = "eine @auto-eager-Regel darf keinen Zeugen aufschieben: jeder Hypothesenbinder muss in der Konklusion vorkommen",
    .err_InvalidTriggerAnnotation = "@auto trigger erwartet ein geklammertes Präfixmuster: (term binder-oder-_ ...)",
    .err_UnknownTriggerTerm = "@auto trigger nennt einen Term, der hier nicht verfügbar ist",
    .err_UnknownTriggerBinder = "@auto trigger verweist auf einen Binder, der nicht zur Regel gehört",
    .err_TriggerRuleHasHypotheses = "eine @auto-trigger-Regel darf keine Hypothesen haben",
    .err_TriggerBinderNotGround = "@auto trigger muss jeden Regelbinder nennen, der nicht auf eine ACUI-Einheit zurückfallen kann",
    .err_TriggerSortMismatch = "eine Position im @auto-trigger-Muster hat die falsche Sorte",
    .err_TriggerBoundPosition = "gebundene Argumentpositionen im @auto-trigger-Muster erlauben nur _",
    .err_FallbackCycle = "die @fallback-Kette enthält einen Zyklus",
    .err_UnknownFreshBinder = "das @fresh-Ziel muss ein echter Regelbinder sein",
    .err_UnknownFreshenBinder = "@freshen verweist auf einen Binder, der nicht zur Regel gehört",
    .err_UnknownAlphaBinder = "@alpha verweist auf einen Binder, der nicht zur Regel gehört",
    .err_DuplicateFreshBinder = "an einem Regelbinder sind mehrere @fresh-Annotationen angebracht",
    .err_DuplicateFreshenPair = "an einer Regel sind mehrere identische @freshen-Annotationen angebracht",
    .err_FreshRequiresBoundBinder = "das @fresh-Ziel muss ein gebundener Regelbinder sein",
    .err_FreshenTargetMustBeRegularBinder = "das @freshen-Ziel muss ein regulärer Regelbinder sein",
    .err_FreshenBlockerMustBeBoundBinder = "der @freshen-Blocker muss ein gebundener Regelbinder sein",
    .err_AlphaRequiresBoundBinders = "beide @alpha-Binder müssen gebundene Regelbinder sein",
    .err_AlphaSortMismatch = "die @alpha-Binder müssen dieselbe Sorte haben",
    .err_AlphaConclusionMustBeBinaryRelation = "die Konklusion einer @alpha-Regel muss eine zweistellige Relation sein",
    .err_AlphaConclusionUnsupported = "die linke Seite einer @alpha-Regel muss eine Termanwendung sein",
    .err_AlphaRuleHasHypotheses = "eine @alpha-Regel darf keine Hypothesen haben",
    .err_InvalidCongruenceAnnotation = "die @congr-Regel hat nicht die erwartete Kongruenzform",
    .err_CongruenceBinderOrderMismatch = "die @congr-Binder müssen in der Reihenfolge old₀ new₀ old₁ new₁ ... stehen",
    .err_CongruenceBinderMissingDeps = "die old/new-Binder von @congr müssen jede Abhängigkeit deklarieren, die das Argument des Kopfterms erlaubt (z. B. (p q: wff x))",
    .err_RelationBundleBoundBinder = "@relation-Bündelregeln (refl/trans/symm/transport) dürfen keine gebundenen Binder haben",
    .err_InvalidConversionAnnotation = "@conversion erwartet ein Token: ltr, rtl, both, assoc oder comm",
    .err_InvalidDefConversionAnnotation = "@conversion an einer Definition erwartet ein Token: unfold, fold oder both",
    .err_ConversionTermNotDef = "@conversion an einem Term erfordert eine Definition mit sichtbarem Definiens",
    .err_ConversionDefUnfoldHiddenDummies = "@conversion unfold/both kann eine Definition mit verborgenen Dummy-Bindern nicht einschreiben: das Entfalten müsste bei jedem Treffer einen Dummy-Zeugen erfinden; nur fold ist hier zulässig",
    .err_DuplicateConversionAnnotation = "an einer Regel sind mehrere @conversion-Annotationen angebracht",
    .err_ConversionRuleHasHypotheses = "eine @conversion-Regel darf keine Hypothesen haben",
    .err_ConversionCommRuleShape = "@conversion comm verlangt die Konklusion rel(t(a, b), t(b, a)) über genau zwei verschiedenen Bindern",
    .err_ConversionAssocRuleShape = "@conversion assoc verlangt die Konklusion rel(t(t(a, b), c), t(a, t(b, c))) (in einer der beiden Richtungen) über genau drei verschiedenen Bindern",
    .err_ConversionAlphaRuleShape = "@conversion alpha verlangt, dass beide Konklusionsseiten denselben Kopf haben, mit genau einem umbenannten gebundenen Binder an einer gebundenen Argumentposition dieses Kopfes, der rechts frisch ist und dieselbe Sorte hat",
    .err_ConversionRoleBoundBinder = "@conversion-assoc/comm-Regeln dürfen keine gebundenen Binder haben",
    .err_ConversionRoleRelationHead = "@conversion assoc/comm kann keinen registrierten @relation-Term zertifizieren: Relationsanwendungen müssen unverändert bleiben, damit lokale Gleichungen direkt zitiert werden können",
    .err_DuplicateConversionRoleForHead = "eine andere @conversion-Regel zertifiziert dieses Gesetz für denselben Operator bereits",
    .err_ConversionConclusionNotRelation = "die Konklusion einer @conversion-Regel muss die Form rel(lhs, rhs) haben",
    .err_ConversionMissingRelation = "der Kopf der @conversion-Konklusion muss der registrierte @relation-Term für seine Operandensorte sein",
    .err_ConversionBareMatchSide = "die Musterseite von @conversion muss eine Termanwendung sein, kein bloßer Binder",
    .err_ConversionBinderNotCovered = "die Musterseite von @conversion muss jeden Binder binden, den die Einsetzungsseite verwendet",
    .err_InvalidComputeAnnotation = "@compute erwartet ein Token: ltr oder rtl",
    .err_DuplicateComputeAnnotation = "diese Regel ist bereits für conversion? eingeschrieben (eine @compute/@conversion-Einschreibung pro Regel)",
    .err_ComputeRuleHasHypotheses = "eine @compute-Regel darf keine Hypothesen haben",
    .err_ComputeConclusionNotRelation = "die Konklusion einer @compute-Regel muss die Form rel(lhs, rhs) haben",
    .err_ComputeMissingRelation = "der Kopf der @compute-Konklusion muss der registrierte @relation-Term für seine Operandensorte sein",
    .err_ComputeBareMatchSide = "die Musterseite von @compute muss eine Termanwendung sein, kein bloßer Binder",
    .err_ComputeBinderNotCovered = "die Musterseite von @compute muss jeden Binder binden, den die Einsetzungsseite verwendet",
    .err_FreshStrictSort = "@fresh kann keinen Binder in einer strikten Sorte anvisieren",
    .err_FreshFreeSort = "@fresh kann keinen Binder in einer freien Sorte anvisieren",
    .err_FreshNoAvailableVar = "@fresh fand kein verfügbares @vars-Token",
    .err_HiddenWitnessNoAvailableVar = "ein verborgener Definitionszeuge brauchte ein frisches @vars-Token, aber keines war verfügbar",
    .err_NoAlphaRewriteAvailable = "für diesen @freshen-Schritt war keine passende @alpha-Regel verfügbar",
    .err_AlphaRewriteSearchFailed = "die verfügbaren @alpha-Regeln haben die Blocker-Abhängigkeit nicht beseitigt",
    .err_DepViolation = "die Binderzuweisungen verletzen die Abhängigkeitsbedingungen der Regel",
    .err_FreshenMissingRelation = "das Freshening braucht eine registrierte Relation auf der betroffenen Sorte",
    .err_FreshenTransportFailed = "das Freshening konnte das Alpha-Rewriting nicht durch die Regelformel heben",
    .err_InvalidHoleAnnotation = "@hole erwartet genau ein rohes Mathe-Token",
    .err_DuplicateHoleAnnotation = "an einer Sorte sind mehrere @hole-Annotationen angebracht",
    .err_DuplicateHoleToken = "doppeltes @hole-Token über Sorten hinweg",
    .err_InvalidVarsAnnotation = "@vars erwartet ein oder mehrere rohe Mathe-Tokens",
    .err_VarsStrictSort = "@vars kann nicht auf einer strikten Sorte verwendet werden",
    .err_VarsFreeSort = "@vars kann nicht auf einer freien Sorte verwendet werden",
    .err_DuplicateVarsToken = "doppeltes @vars-Token über Sorten hinweg",
    .err_VarsTokenCollision = "das @vars-Token kollidiert mit einem bestehenden Term, einer Notation oder einem Formelmarker",
    .err_DependencySlotExhausted = "das Theorem überschreitet die 55 verfolgten Abhängigkeitsplätze für gebundene Variablen",
    .err_UnresolvedDummyWitness = "die Regel passte durch verborgene Definitionsstruktur, aber ausgelassene Binder enthalten unaufgelöste Zeugen für verborgene Dummys",
    .err_MissingCongruenceRule = "für die Normalisierung fehlt eine benötigte Kongruenzregel",
    .err_ExpectedIdentifier = "Bezeichner erwartet",
    .err_ExpectedNumber = "Zahl erwartet",
    .err_UnknownMathToken = "unbekanntes Token im Mathe-String",
    .err_ExpectedMathToken = "Token im Mathe-String erwartet",
    .err_ExpectedCloseParen = "schließende Klammer im Mathe-String erwartet",
    .err_TrailingMathTokens = "unerwartete Tokens am Ende des Mathe-Strings",
    .err_NotationMismatch = "die Tokenfolge passt nicht zur deklarierten Notation",
    .err_AnonymousNotationBinder = "anonyme Binder sind in Notationsdeklarationen nicht zulässig",
    .err_DummyNotationBinder = "Dummy-Binder sind in Notationsdeklarationen nicht zulässig",
    .err_InvalidNotationVariables = "die Notation muss jedes deklarierte Argument genau einmal erwähnen",
    .err_PrecMismatch = "die Operatorpräzedenz lässt diese Lesart nicht zu",
    .err_NotProvable = "der Mathe-String hat keine beweisbare Sorte",
    .err_ExpectedMathString = "$...$-Mathe-String erwartet",
    .err_PublicDefBodyMustBeHeaderless = "die Ergänzung eines öffentlichen Definitionsrumpfs darf vor `=` nur Dummy-Binder deklarieren",
    .err_FillerBinderMustBeDummy = "Ergänzungsbinder eines öffentlichen Definitionsrumpfs müssen verborgene Dummys wie (.x: s) sein",
    .err_DuplicateFillerBinderName = "der Name des Ergänzungs-Dummys ist durch die Definition bereits gebunden",
    .err_TooManyBoundVars = "eine Deklaration darf höchstens 55 Variablen binden (gebundene Binder und verborgene Dummys zusammen)",
    .err_ExtraProofItem = "überzähliges Beweiselement ohne zugehörige Deklaration",
    .err_ExpectedBy = "'by' nach der Aussage der Beweiszeile erwartet",
    .err_ExpectedKeyword = "Schlüsselwort erwartet",
    .err_ExpectedString = "String in Anführungszeichen erwartet",
    .err_UnknownTerm = "unbekannter Term",
    .err_UnknownSort = "unbekannte Sorte",
    .err_UnknownVariable = "unbekannte Variable",
    .err_UnexpectedKeyword = "unerwartetes Schlüsselwort",
    .err_UnexpectedCharacter = "unerwartetes Zeichen",
    .err_ExpectedLineEnd = "Zeilenende erwartet",
    .err_ExpectedBlockUnderline = "Unterstreichung nach der Kopfzeile des Beweisblocks erwartet",
    .err_UnterminatedMathString = "nicht abgeschlossener $...$-Mathe-String",
    .err_UnterminatedString = "nicht abgeschlossener String",
    .err_ExpectedDefEquals = "'=' im beweisseitigen Definitionsrumpf erwartet",
    .err_ExpectedProofBlock = "Beweisblock erwartet",
    .err_OutOfMemory = "dem Compiler ist der Speicher ausgegangen",
    .err_UnexpectedInternalError = "unerwarteter interner Fehler; bitte melden Sie dies",
    .err_UnknownDummyVar = "interner Fehler: unbekannte Dummy-Variable; bitte melden Sie dies",
    .err_UnknownPlaceholder = "interner Fehler: unbekannter Platzhalter; bitte melden Sie dies",
    .err_PlaceholderLeakage = "in diesem Beweis verbleibt ein unaufgelöster Suchplatzhalter",
    .err_UnsolvedMetaLeakage = "in diesem Beweis verbleibt eine ungelöste Metavariable",
    .err_Overflow = "eine interne Grenze wurde überschritten; das Theorem ist womöglich zu groß",
    .err_TooManyTheoremExprs = "das Theorem ist zu groß (interne Ausdrucksgrenze überschritten)",
    .err_HoleNotConcrete = "ein Beweisloch ist hier nicht zulässig",
    .err_HoleNotAllowedInTemplate = "ein Beweisloch ist in einer Regelaussage nicht zulässig",
    .err_TooManyCompilerRules = "zu viele Regeln deklariert",
    .err_TooManyCompilerTerms = "zu viele Terme deklariert (Compiler-Grenze)",
    .err_UnknownTemplateVariable = "interner Fehler: unbekannte Vorlagenvariable; bitte melden Sie dies",
    .err_InvalidExprUseCount = "interner Fehler bei der Beweisausgabe; bitte melden Sie dies",
    .err_TooManyTheoremVars = "das Theorem hat zu viele Variablen",
    .err_ExpectedDefinitionBody = "die Definition hat keinen Rumpf",
    .err_ArgCountMismatch = "falsche Anzahl von Argumenten für den Term",
    .err_DummyHypothesisBinder = "Hypothesenbinder können keine Dummys sein",
    .err_DuplicateSort = "doppelter Sortenname",
    .err_DuplicateTermName = "doppelter Term- oder Definitionsname",
    .err_ExpectedFormula = "Formel erwartet",
    .err_TooManySorts = "zu viele Sorten deklariert",
    .err_TooManyTerms = "zu viele Terme deklariert",
    .err_UnexpectedHypothesisBinder = "Hypothesenbinder sind in dieser Deklaration nicht zulässig",
    .err_UnexpectedTrailingInput = "unerwartete Eingabe nach dem Ende der Aussage",
    .err_UnexpectedEOF = "unerwartetes Dateiende",
    .err_NumberOutOfRange = "die Zahl ist zu groß (höchstens 65535)",
    .err_MultiCharacterDelimiter = "Trennzeichen müssen einzelne Zeichen sein",
    .err_InvalidNotationToken = "'(' und ')' können nicht als Notations-Tokens verwendet werden",
    .err_PrecedenceMismatch = "das Token wurde bereits mit einer anderen Präzedenz deklariert",
    .err_PrecedenceAssocMismatch = "diese Präzedenzstufe wurde bereits mit der entgegengesetzten Assoziativität deklariert",
    .err_NotationFirstTokenConflict = "das erste Token einer Notation kann nicht zugleich ein Präfix- oder Infix-Token sein",
    .err_ExpectedBinaryOperator = "eine Infix-Notation erfordert einen Term mit genau zwei Argumenten",
    .err_ExpectedUnaryOperator = "eine Präfix-Notation erfordert einen Term mit genau einem Argument",
    .err_InfixPrecOutOfRange = "die Präzedenz des Infix-Operators liegt außerhalb des zulässigen Bereichs",
    .err_CoercionCycle = "die Coercion würde einen Zyklus zwischen Sorten erzeugen",
    .err_CoercionDiamond = "die Coercion würde einen zweiten Weg zwischen zwei Sorten erzeugen (Coercion-Pfade müssen eindeutig sein)",
    .err_CoercionDiamondToProvable = "die Coercion würde einen zweiten Weg zu einer beweisbaren Sorte erzeugen",
    .err_UnnamedRuleBinder = "die Binderzuweisung zielt auf einen unbenannten Regelbinder",

    // Note messages (renderNoteMessage).
    .note_missing_semicolon_hint = "meist fehlt ein ';' am Ende der Deklaration vor dieser Stelle",
    .note_unknown_math_token_hint = "das Token ist weder eine Variable dieses Theorems noch ein Term oder eine Notation der Theorie",
    .note_trailing_math_token_hint = "der Ausdruck links parst für sich allein; dieses Token ist keine Notation, die ihn erweitern kann",
    .note_search_placeholder_meaning = "Suchplatzhalter (auto?, exact?, apply?, conversion?) stehen für eine Suche, die im Editor läuft und durch den gefundenen Beweis ersetzt wird",
    .note_search_placeholder_unfinished = "der Compiler prüft nur fertige Beweise; diese Suche hat noch keinen geliefert",
    .note_rule_declared_later = "die Regel wird später in der mm0-Datei deklariert",
    .note_name_is_term_not_rule = "dieser Name ist ein Term oder eine Definition; er kann in Formeln vorkommen, aber keine Beweiszeile rechtfertigen",
    .note_name_is_label_not_rule = "dieser Name ist ein Beweiszeilen-Label, keine Regel; frühere Zeilen werden in den Klammern nach einer Regel als Prämissen zitiert",
    .note_label_belongs_to_later_line = "dieses Label gehört zu einer späteren Zeile; eine Zeile kann nur die Zeilen über ihr zitieren",
    .note_def_body_result_sort = "der Definitionsrumpf muss bereits die deklarierte Ergebnissorte haben",
    .note_def_body_checked_before_unify = "Definitionsrümpfe werden geprüft, bevor der Def-Unify-Strom läuft",
    .note_def_body_free_var_deps = "jede freie Variable des Rumpfs muss als Abhängigkeit des Ergebnistyps deklariert sein",
    .note_subexpression_sort_mismatch = "ein Teilausdruck wird hier verwendet, wo eine andere Sorte erwartet ist",
    .note_subexpression_needs_bound_var = "eine Position in diesem Ausdruck erfordert eine einzelne gebundene Variable",
    .note_right_sort_but_needs_bound_var = "die Zuweisung parst mit der richtigen Sorte, aber dieser Binder erfordert eine einzelne gebundene Variable",
    .note_holey_fallback_exhausted = "die Fallback-Kette für die lückenhafte Aussage ist erschöpft; gezeigt wird der erste fehlgeschlagene Kandidat",
    .note_visible_structure_mismatch = "die sichtbaren Teile der Aussage stimmen nicht mit der Konklusion der Regel überein",
    .note_unnamed_rule_var_two_values = "eine Regelvariable bräuchte zwei verschiedene Werte",
    .note_attempted_normalized_comparison = "normalisierter Vergleich wurde versucht",
    .note_boundary_mismatch_despite_unfolding = "die beiden stimmen nicht überein, selbst mit entfalteten Definitionen",
    .note_boundary_mismatch_despite_normalization = "auch nach Normalisierung nicht",
    .note_conclusion_replay_mismatch = "die Aussage stimmt nicht mit der Konklusion der Regel überein",
    .note_identical_positions_matched_differently = "zwei Positionen, die die Regel als identisch verlangt, passten auf verschiedene Ausdrücke",
    .note_no_rule_var_completion = "keine Belegung der Regelvariablen bringt sie zur Übereinstimmung",
    .note_rule_requires_bound_var_here = "die Regel erfordert hier eine einzelne gebundene Variable",
    .note_assignment_parses_as_sort = "die Zuweisung parst, aber mit Sorte '{s}'; dieser Binder erwartet Sorte '{s}'",
    .note_statement_not_provable_sort = "die Aussage parst, aber mit Sorte '{s}', die keine beweisbare Sorte ist",
    .note_premise_hypothesis_mismatch = "die zitierte Prämisse {0d} passt nicht zu Hypothese {0d} der Regel",
    .note_cited_premise_proves = "die zitierte Prämisse beweist: {s}",
    .note_holey_unsolved_binder = "die lückenhafte Aussage ließ den Binder {s} ungelöst",
    .note_unsolved_binder_index = "Index des ungelösten Binders: {d}",
    .note_conclusion_head_clash = "die Konklusion der Regel hat '{s}', wo die Aussage '{s}' hat",
    .note_conclusion_head_clash_with_variable = "die Konklusion der Regel hat '{s}', wo die Aussage eine Variable hat",
    .note_rule_var_two_values = "die Regelvariable {s} bräuchte zwei verschiedene Werte",
    .note_already_matched = "bereits zugeordnet: {s}",
    .note_in_the_statement = "in der Aussage: {s}",
    .note_at_the_mismatch = "an der Abweichungsstelle: {s}",
    .note_hole_sort_mismatch = "Loch {s} erwartete Sorte {s}, passte aber auf {s}",
    .note_expected_expr = "erwartet: {s}",
    .note_actual_expr = "tatsächlich: {s}",
    .note_normalized_expected_expr = "normalisiert erwartet: {s}",
    .note_normalized_actual_expr = "normalisiert tatsächlich: {s}",
    .note_freshen_attempted_for_target = "@freshen für Ziel-Binder {s} versucht",
    .note_freshen_blocker = "Blocker-Binder des Freshening: {s}",
    .note_freshen_replacement = "gewählter Ersatzbinder: {s}",
    .note_freshen_still_depends_on_blocker = "das umgeschriebene Ziel hängt weiterhin vom Blocker-Binder {s} ab",
    .note_freshen_no_longer_depends_on_blocker = "das umgeschriebene Ziel hängt nicht mehr vom Blocker-Binder {s} ab",
    .note_theorem_concludes = "das Theorem schließt: {s}",
    .note_last_line_proves = "die letzte Zeile beweist: {s}",
    .note_explicit_bindings = "explizite Zuweisungen: {s}",
    .note_inferred_bindings_before_failure = "vor dem Fehlschlag erschlossene Zuweisungen: {s}",
    .note_rule_requires_term_at_mismatch = "die Regel verlangt '{s}' an der Abweichungsstelle, gefunden wurde: {s}",
    .note_chosen_bindings = "gewählte Zuweisungen: {s}",
    .note_alternative_bindings = "alternative Zuweisungen: {s}",
    .note_distinct_solutions_considered = "verschiedene betrachtete Lösungen: {d}",
    .note_binder_resolved_to = "dieser Binder wurde aufgelöst zu: {s}",
    .note_binding_sort_mismatch = "sie hat Sorte '{s}', aber die Regel erwartet hier Sorte '{s}'",
    .note_inference_path = "Inferenzpfad: {s}",

    // Related-location labels.
    .related_rule_declaration_here = "die Regel wird hier deklariert",

    // Missing-congruence summaries.
    .congr_missing_rule_for_term = "fehlendes @congr für Term {s}",
    .congr_missing_rule = "fehlende @congr-Regel",
    .congr_changed_bound_arg_term = "das gebundene Argument {0d} von Term {1s} hat sich während der Normalisierung geändert",
    .congr_changed_bound_arg = "das gebundene Argument {d} hat sich während der Normalisierung geändert",
    .congr_changed_bound_arg_generic = "ein gebundenes Argument hat sich während der Normalisierung geändert",
    .congr_missing_child_relation_term = "fehlende Relation für Argument {0d} von Term {1s}",
    .congr_missing_child_relation_arg = "fehlende Relation für Argument {d}",
    .congr_missing_child_relation = "fehlende Kindrelation",
    .congr_missing_child_proof_term = "Argument {0d} von Term {1s} hat sich ohne Kongruenzbeweis geändert",
    .congr_missing_child_proof_arg = "Argument {d} hat sich ohne Kongruenzbeweis geändert",
    .congr_missing_child_proof = "ein Argument hat sich ohne Kongruenzbeweis geändert",
    .congr_missing_parent_relation_term = "fehlende Elternrelation für Term {s}",
    .congr_missing_parent_relation = "fehlende Elternrelation",
    .congr_malformed_rule_term = "fehlgeformte @congr-Regel für Term {s}",
    .congr_malformed_rule = "fehlgeformte @congr-Regel",
    .congr_unknown_term = "die Normalisierung verwendete einen unbekannten Term",

    // Dependency-violation and omission summaries.
    .omitted_diagnostics_count = "{d} weitere Diagnosen ausgelassen",
    .dep_bound_distinct = "den gebundenen Variablen {0s} und {1s} müssen verschiedene Variablen zugewiesen werden",
    .dep_regular_mentions_bound = "die Regel erlaubt nicht, dass {0s} die Variable erwähnt, die {1s} zugewiesen wurde",
    .dep_conflicting_binders = "Binder {0s} und {1s} stehen im Konflikt",
    .dep_assignment = "{0s} wurde zugewiesen: {1s}",
    .detail_dep_violation_prefix = "Abhängigkeitsverletzung: ",
    .detail_missing_congruence_prefix = "fehlende Kongruenz: ",

    // Diagnostic context lines.
    .ctx_theorem = "Theorem: {s}",
    .ctx_proof_block = "Beweisblock: {s}",
    .ctx_line = "Zeile: {s}",
    .ctx_rule = "Regel: {s}",
    .ctx_name = "Name: {s}",
    .ctx_expected = "erwartet: {s}",
    .ctx_phase = "Phase: {s}",
    .ctx_sort = "Sorte: {s}",

    // Diagnostic detail lines.
    .detail_token = "Token: {s}",
    .detail_did_you_mean = "meinten Sie: {s}",
    .detail_expected_char = "erwartet: '{c}'",
    .detail_missing_binder = "fehlender Binder: {s}",
    .detail_inference_path = "Inferenzpfad: {s}",
    .detail_first_unsolved_binder = "erster ungelöster Binder: {s}",
    .detail_declared_sort = "deklarierte Sorte: {s}",
    .detail_actual_sort = "tatsächliche Sorte: {s}",
    .detail_body_deps = "Rumpfabhängigkeiten: 0x{x}",
    .detail_hidden_binders = "verborgene Binder: {d}",
    .detail_hypothesis_ref_name = "Hypothesenreferenz: #{s}",
    .detail_hypothesis_ref_index = "Hypothesenreferenz: #{d}",
    .detail_parameter = "Parameter: {s}",

    // Inference-path names.
    .path_strict_replay = "exakte Übereinstimmung",
    .path_transparent_fallback = "Abgleich mit entfalteten Definitionen",
    .path_normalized_session_fallback = "Abgleich nach Normalisierung",
    .path_structural_solver = "struktureller Abgleich",
    .path_holey_surface_match = "Abgleich der lückenhaften Aussage",

    // Phase names.
    .phase_parse = "Parsen",
    .phase_inference = "Inferenz",
    .phase_theorem_application = "Theoremanwendung",
    .phase_freshen = "Freshening",
    .phase_normalization = "Normalisierung",
    .phase_final_reconciliation = "Abschlussabgleich",
};

pub inline fn table(comptime lang: Lang) Strings {
    return switch (lang) {
        .en => en,
        .de => de,
    };
}
